In [50]:
import pandas as pd

file = '/Users/evaberry/Documents/ESILV A4/PI2/Dataset final/Updated_SENED_Budget_Solidarity_Syria-Turkey_2023_05_17_EN - NamesCoded.xlsx'

# Extraction of the data and export of it into dataframes

In [51]:
# First dataframe : line 1 to 31  
df1 = pd.read_excel(file, skiprows=0, nrows=31)

# Second dataframe : line 39 to 42 
df2 = pd.read_excel(file, skiprows=38, nrows=4)

# Third dataframe : line 48 to 54 
df3 = pd.read_excel(file, skiprows=47, nrows=7)

# Fourth dataframe : line 59 to 60 
df4 = pd.read_excel(file, skiprows=58, nrows=2)

# Dataframe 1 : Human resources

In [52]:
df1

,!!Please insert lines under the sub-headings if necessary!!,Unnamed: 1,!! Pay attention not to erase formulas in the blue cells !!,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,"If this table is filled up, no need to fill in the ""project budget in euros"" sheet",Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
0,Name of the person in charge of the budget,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Name of the applicant NGO,NaN,Sened Organization,NaN,NaN,NaN,NaN,Euro exchange rate\n€ / USD,NaN,0.047,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Project title,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Expenditure related to the project\nRecommenda...,Unit,Number of units,Unit cost in EUR,Total cost in EUR,NaN,Year 1 in TRY,Year 2 in TRY,Year 3 in TRY,...,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,2024-11-01 00:00:00,2024-12-01 00:00:00,2025-01-01 00:00:00,2025-02-01 00:00:00,TOTAL EXPENSES,%,Remaining
4,1,Human resources dedicated to the project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.1,Salaries and employer's contributions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Salary for coordination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1.1.01,IT and Media Officer (50%) TR,per month,6,1650,NaN,NaN,NaN,NaN,NaN,...,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1.1.02,MHPSS Technical Specialist (10%) TR,per month,6,3500,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1.1.03,Supply Chain Coordinator (10%) TR,per month,6,3100,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1.1.04,Project Coordinator (10%) TR,per month,6,3100,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1.1.05,Inclusion Technical Specialist (10%) SY,per month,6,850,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1.1.06,MEAL Coordinator (10%) TR,per month,6,3100,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1.1.07,HR Coordinator (10%) TR,per month,6,3100,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1.1.08,Finance Coordiantor (10%) TR,per month,6,3100,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Salary for operational staff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1.1.08,Project Officer (100%) TR,per month,5,1650,8250,NaN,NaN,NaN,NaN,...,1441.423048,1368.768127,1354.158382,1392.999206,1415.526133,1812.286963,1807.630615,10592.792474,1.283975,-2342.792474
17,1.1.09,Finance Assistant (100%) TR,per month,5,800,4000,NaN,NaN,NaN,NaN,...,333.034227,1060.317027,1048.856897,-1.238812,0,1432.877904,1429.408764,5303.256008,1.325814,-1303.256008
18,1.1.10,Supply Assistant (100%) TR,per month,5,800,4000,NaN,NaN,NaN,NaN,...,0,1368.768127,1354.158382,-0.980266,0,1285.468364,1280.447933,5287.86254,1.321966,-1287.86254
19,1.1.11,Child safeguarding specalist (15%),per month,5,300,1500,NaN,NaN,NaN,NaN,...,0,743.456675,565.018713,329.781999,119.862011,374.343555,377.459818,2509.922772,1.673282,-1009.922772
20,1.1.12,Case Manager*1 (100%) - SY,per month,5,700,3500,NaN,NaN,NaN,NaN,...,0,572.342067,588.36843,607.02616,622.749335,686.616079,689.319546,3766.421617,1.07612,-266.421617
21,1.1.13,Case Officer*1 ( 100%)-SY,per month,5,500,2500,NaN,NaN,NaN,NaN,...,0,136.63482,452.5911,186.77728,0,1110.6884,586.3686,2473.0602,0.989224,26.9398
22,1.1.14,PSS Officer*2 (100%) - SY,per month,10,500,5000,NaN,NaN,NaN,NaN,...,0,15.187659,0,0,0,902.587523,1014.879083,1932.654265,0.386531,3067.345735
23,1.1.15,Inclusion Sr.Officer (100%) SY,per month,5,650,3250,NaN,NaN,NaN,NaN,...,0,0,588.36843,607.02616,622.749335,686.616079,689.319546,3194.07955,0.982794,55.92045
24,1.1.16,SNR Officer*1 (100%) - SY,per month,5,500,2500,NaN,NaN,NaN,NaN,...,0,0,0,217.900662,479.03795,541.556344,543.688656,1782.183612,0.712873,717.816388
25,1.1.17,Case Worker*4 (100%) - SY,per month,20,375,7500,NaN,NaN,NaN,NaN,...,0,456.973577,1024.352573,980.58072,1341.30626,1189.489827,1205.737256,6198.440213,0.826459,1301.559787
26,1.1.18,PSS Facilitator*4 (100%) - SY,per month,20,375,7500,NaN,NaN,NaN,NaN,...,0,0,464.657179,1263.871923,1330.122384,1438.121255,1196.662961,5693.435703,0.759125,1806.564297
27,1.1.19,Media Officer (100%) - SY,per month,5,500,2500,NaN,NaN,NaN,NaN,...,0,440.261741,452.5911,466.9432,479.03795,541.556344,543.688656,2924.078991,1.169632,-424.078991
28,1.1.21,Driver (100%) - SY,per month,5,200,1000,NaN,NaN,NaN,NaN,...,0,0,30.194754,911.754596,191.61518,251.436874,252.426876,1637.42828,1.637428,-637.42828
29,1.1.22,Cleaner (100%) - SY,per month,5,200,1000,NaN,NaN,NaN,NaN,...,0,0,0,101.164862,239.518975,299.790119,0,640.473956,0.640474,359.526044
30,1.2,Honoraires experts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In the df1 dataframe, we have new lines that appears because in reality those lines are hidden in the excel sheet. So, we need to understand why those values are hidden.

**Delete of the fourth first rows:**

In [53]:
df1 = df1.iloc[3:].reset_index(drop=True)
df1.columns = df1.iloc[0]      
df1 = df1[1:].reset_index(drop=True)

In [54]:
df1

,NaN,Expenditure related to the project\nRecommendations,Unit,Number of units,Unit cost in EUR,Total cost in EUR,NaN,Year 1 in TRY,Year 2 in TRY,Year 3 in TRY,...,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,2024-11-01 00:00:00,2024-12-01 00:00:00,2025-01-01 00:00:00,2025-02-01 00:00:00,TOTAL EXPENSES,%,Remaining
0,1,Human resources dedicated to the project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.1,Salaries and employer's contributions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Salary for coordination,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.1.01,IT and Media Officer (50%) TR,per month,6,1650,NaN,NaN,NaN,NaN,NaN,...,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.1.02,MHPSS Technical Specialist (10%) TR,per month,6,3500,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.1.03,Supply Chain Coordinator (10%) TR,per month,6,3100,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1.1.04,Project Coordinator (10%) TR,per month,6,3100,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1.1.05,Inclusion Technical Specialist (10%) SY,per month,6,850,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1.1.06,MEAL Coordinator (10%) TR,per month,6,3100,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1.1.07,HR Coordinator (10%) TR,per month,6,3100,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1.1.08,Finance Coordiantor (10%) TR,per month,6,3100,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Salary for operational staff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1.1.08,Project Officer (100%) TR,per month,5,1650,8250,NaN,NaN,NaN,NaN,...,1441.423048,1368.768127,1354.158382,1392.999206,1415.526133,1812.286963,1807.630615,10592.792474,1.283975,-2342.792474
13,1.1.09,Finance Assistant (100%) TR,per month,5,800,4000,NaN,NaN,NaN,NaN,...,333.034227,1060.317027,1048.856897,-1.238812,0,1432.877904,1429.408764,5303.256008,1.325814,-1303.256008
14,1.1.10,Supply Assistant (100%) TR,per month,5,800,4000,NaN,NaN,NaN,NaN,...,0,1368.768127,1354.158382,-0.980266,0,1285.468364,1280.447933,5287.86254,1.321966,-1287.86254
15,1.1.11,Child safeguarding specalist (15%),per month,5,300,1500,NaN,NaN,NaN,NaN,...,0,743.456675,565.018713,329.781999,119.862011,374.343555,377.459818,2509.922772,1.673282,-1009.922772
16,1.1.12,Case Manager*1 (100%) - SY,per month,5,700,3500,NaN,NaN,NaN,NaN,...,0,572.342067,588.36843,607.02616,622.749335,686.616079,689.319546,3766.421617,1.07612,-266.421617
17,1.1.13,Case Officer*1 ( 100%)-SY,per month,5,500,2500,NaN,NaN,NaN,NaN,...,0,136.63482,452.5911,186.77728,0,1110.6884,586.3686,2473.0602,0.989224,26.9398
18,1.1.14,PSS Officer*2 (100%) - SY,per month,10,500,5000,NaN,NaN,NaN,NaN,...,0,15.187659,0,0,0,902.587523,1014.879083,1932.654265,0.386531,3067.345735
19,1.1.15,Inclusion Sr.Officer (100%) SY,per month,5,650,3250,NaN,NaN,NaN,NaN,...,0,0,588.36843,607.02616,622.749335,686.616079,689.319546,3194.07955,0.982794,55.92045
20,1.1.16,SNR Officer*1 (100%) - SY,per month,5,500,2500,NaN,NaN,NaN,NaN,...,0,0,0,217.900662,479.03795,541.556344,543.688656,1782.183612,0.712873,717.816388
21,1.1.17,Case Worker*4 (100%) - SY,per month,20,375,7500,NaN,NaN,NaN,NaN,...,0,456.973577,1024.352573,980.58072,1341.30626,1189.489827,1205.737256,6198.440213,0.826459,1301.559787
22,1.1.18,PSS Facilitator*4 (100%) - SY,per month,20,375,7500,NaN,NaN,NaN,NaN,...,0,0,464.657179,1263.871923,1330.122384,1438.121255,1196.662961,5693.435703,0.759125,1806.564297
23,1.1.19,Media Officer (100%) - SY,per month,5,500,2500,NaN,NaN,NaN,NaN,...,0,440.261741,452.5911,466.9432,479.03795,541.556344,543.688656,2924.078991,1.169632,-424.078991
24,1.1.21,Driver (100%) - SY,per month,5,200,1000,NaN,NaN,NaN,NaN,...,0,0,30.194754,911.754596,191.61518,251.436874,252.426876,1637.42828,1.637428,-637.42828
25,1.1.22,Cleaner (100%) - SY,per month,5,200,1000,NaN,NaN,NaN,NaN,...,0,0,0,101.164862,239.518975,299.790119,0,640.473956,0.640474,359.526044
26,1.2,Honoraires experts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Dataframe 2 : Travel cost

In [55]:
df2

,2,Travel costs,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
0,2.1,2 Cars for mobile team and benfiaries,per month,2.0,6000.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.2,Fuel for 2 cars,per month,5.0,200.0,1000.0,NaN,NaN,NaN,NaN,...,0.0,131.67448,126.725508,166.72064,530.24645,738.7475,456.03993,2150.154508,2.150155,-1150.154508
2,2.3,Travel cost from Turkey to Syria for managemen...,per month,5.0,200.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sub- total 2 Travel costs,NaN,NaN,NaN,NaN,1000.0,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Dataframe 3 : Travel cost part two

In [56]:
df3

,3.1.4,Water dispenser,per item,2,200,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38
0,3.1.6,Supplies and Stationary,lumpsum,1.0,400.000000,400.000000,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0000,0.000000,321.108903,321.108903,0.802772,78.891097
1,3.1.7,Refreshment for activities,lumpsum,1.0,400.000000,400.000000,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0000,104.557908,96.812610,201.370518,0.503426,198.629482
2,3.1.8,PSS Kits for chilren,lumpsum,1.0,7500.000000,7500.000000,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0000,5862.347424,0.000000,5862.347424,0.781646,1637.652576
3,3.1.9,PSS Kits for adults,lumpsum,1.0,7500.000000,7500.000000,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.000000,0.0000,4678.181241,0.000000,4678.181241,0.623757,2821.818759
4,3.1.10,Printing MEAL materials,lumpsum,6.0,84.848485,509.090909,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,261.301415,199.2039,0.000000,0.000000,460.505315,0.904564,48.585594
5,3.1.11,Montessori tools,lumpsum,1.0,1000.000000,1000.000000,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,522.649524,0.0000,0.000000,0.000000,522.649524,0.522650,477.350476
6,Sub-total 3 Material and supplies,NaN,NaN,NaN,NaN,17309.090909,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Dataframe 4 : other costs

In [57]:
df4

,4.3,Office running cost A'zaz with Mobile bills forproject staff,per month,6,183.333333,1100.0,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,0.5,0.6,0.7,2163.910726,0.8,2227.365061,158.25127,4549.527058,4.135934,-3449.527058
0,4.5,ECF,per beneficiary,350.0,50.0,17500,NaN,NaN,NaN,NaN,...,0,0,0,0,89.342895,3071.167874,15066.645051,18227.15582,1.041552,-727.15582
1,4.6,Case management support,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,0,0,0,0,0.000000,0.000000,0.000000,0.00000,NaN,0.00000